### ISSUE TITLE
CachedDataServer persistent data

### ISSUE THREAD

**Issue by julianrace** [OceanDataTools/openrvdas#155]
CachedDataServer should store its cache in some fashion so that the data isn't lost in a crash or service reboot. 

E.G. if you restart OpenRVDAS, cached data server should pick up where it left off with only a gap for the outage.

**Comment by davidpablocohn** [comment]
Closed in dev branch as of 4751f16.

**Comment by davidpablocohn** [comment]
Latest thought: use in-memory cache primarily (for speed), but also write to diskcache in background, with one cache per field. That will allow us to use diskcache's "expire" functionality natively. Only ever need to read diskcache on startup. Need to cull size of disk cache in terms of memory instead of items, though.

For now, manual once-every-minute caching seems to be working fine. Let's stick with that for the moment and hit more urgent issues first.

**Comment by davidpablocohn** [comment]
From Webb: I would think you could build a buffer using MongoDB.  Basically each stream gets it’s own Mongo document.  When new data points arrive the records are added to the beginning of the corresponding document followed immediately by an operation to truncated the document either by number of records or by timestamp.

I’ve hammered Mongo with 10k writes/sec without issue so this approach theoretically could work.

The other nice thing about Mongo is it doesn’t use rigid schemas… therefore accommodating various string types should pose no issues.

**Comment by davidpablocohn** [comment]
Current caching is good enough for 1.0.

Consider using Influx/Mongo for 1.1

**Comment by davidpablocohn** [comment]
Given move toward InfluxDB, going to declare this Good Enough.
